apps/appointments/urls.py
from django.urls import path
from .views import (
    AppointmentIndexView,
    AppointmentCreateView,
    get_occupied_times
)

app_name="appointments"

urlpatterns = [
    path('', AppointmentIndexView.as_view(), name="index"),
    path('create/', AppointmentCreateView.as_view(), name="create"),
    path('occupied-times/', get_occupied_times, name='get_occupied_times'),
]

apps/services/urls.py
from django.urls import path
from .views import (
    ServicesIndexView,
    ServicesCreateView,
    ServicesUpdateView,
    ServicesDeleteView,
)

app_name="services"

urlpatterns = [
    path('', ServicesIndexView.as_view(), name="index"),
    path('create/', ServicesCreateView.as_view(), name="create"),
    path('update/<int:pk>/', ServicesUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', ServicesDeleteView.as_view(), name="delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.home.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('services/', include('apps.services.urls')),
    path('appointments/', include('apps.appointments.urls')),
    path('',home_view, name='home'),
    #path("login/", home_view, name="login"),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/appointments/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.forms import ValidationError
from django.utils import timezone
from datetime import time
from apps.services.models import Services

class Appointment(models.Model):
    service = models.ForeignKey(Services, on_delete=models.DO_NOTHING) # Field for the service of the appointment
    date = models.DateField()  # Field for the date of the appointment
    time = models.TimeField()  # Field for the time of the appointment
    price = models.DecimalField(max_digits=10, decimal_places=2)  # Field for the price of the appointment
    created_at = models.DateTimeField(auto_now_add=True)  # Time when the appointment was created

    def __str__(self):
        return f"{self.service.name} - {self.date} at {self.time}"

    class Meta:
        unique_together = ('date', 'time')
        db_table = 'appointments'
        ordering = ['date', 'time']
    
    def clean(self):
        # Definir los límites de hora
        if not time(8, 0) <= self.time <= time(18, 0):
            raise ValidationError("The time must be between 8:00 am and 6:00 pm.")
        
        # Chequear si la hora está ocupada
        if Appointment.objects.filter(date=self.date, time=self.time).exists():
            raise ValidationError("There is already an appointment reserved for this date and time.")

apps/appointments/forms.py
from datetime import datetime
from django import forms
from .models import Appointment

class AppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #date value is set to today by default
        self.fields['date'].initial = datetime.now().date()
    class Meta:
        model = Appointment
        fields = ['service', 'price', 'date', 'time']
        # fields = ['service', 'price', 'date']
        widgets = {
            'time': forms.Select(attrs={
                #'type': 'time',  # HTML5 time input
                # 'min': '08:00',
                # 'max': '18:00',
                'class': 'form-control',
                'placeholder': 'Select a date first',
            }),
            'date': forms.DateInput(attrs={
                'type': 'date',  # HTML5 date input
                'class': 'form-control',
                'min': datetime.now().date(),
                'placeholder': 'Select a date',
                'onchange': 'onchange_date(this.value)'
            }),
            'service': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Select a service',
            }),
            'price': forms.NumberInput(attrs={
                'class': 'form-control',
                'step': '0.01',
                'min': '0',
                'placeholder': 'Price',
            }),
        }
        labels = {
            'service': 'Service',
            'price': 'Price',
            'date': 'Date',
            'time': 'Time',
        }

apps/appointments/views.py
from datetime import datetime, time, timedelta
from typing import Any
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django_filters.views import FilterView
from .models import Appointment
from .filters import AppointmentFilter
from .forms import AppointmentForm
# Create your views here.

class AppointmentIndexView(LoginRequiredMixin, FilterView):
    model = Appointment
    template_name = "appointments/index.html"
    filterset_class = AppointmentFilter
    paginate_by = 10
    context_object_name = "appointments"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["title"] = "Appointments"
        return context
    
class AppointmentCreateView(LoginRequiredMixin, CreateView):
    model = Appointment
    template_name = "appointments/create.html"
    form_class = AppointmentForm
    success_url = reverse_lazy("appointments:index")

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["title"] = "Create Appointment"
        if self.request.htmx:
            selected_date = self.request.GET.get('date')
            if selected_date:
                # Filtrar las horas ocupadas para la fecha seleccionada
                occupied_times = Appointment.objects.filter(date=selected_date).values_list('time', flat=True)
                context['occupied_times'] = occupied_times
        return context

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        self.object = None
        form = self.get_form()

        if not form.is_valid():
            context = self.get_context_data()
            context["form"] = form
            return render(request, self.template_name, context)

        self.object = form.save()
        messages.success(request, "Appointment was created successfully")
        return HttpResponse(200)
    
def get_occupied_times(request):
    date = request.GET.get('date') 
    date = datetime.strptime(date, '%Y-%m-%d').date()

    if date:
        # Filtrar las citas existentes por la fecha seleccionada
        occupied_appointments = Appointment.objects.filter(date=date).values_list('time', flat=True)
        occupied_times = [appt.strftime("%H:%M") for appt in occupied_appointments]

        # Generar las horas disponibles de 8:00 a 18:00
        start_time = time(8, 0)
        end_time = time(18, 0)
        time_slots = []
        current_time = start_time

        while current_time < end_time:
            time_str = current_time.strftime("%H:%M")
            if time_str not in occupied_times:
                time_slots.append(time_str)
            current_time = (datetime.combine(date.today(), current_time) + timedelta(minutes=60)).time()

        return JsonResponse({'available_times': time_slots})

    return JsonResponse({'error': 'No date provided'}, status=400)

apps/appointments/templates/appointments/create.html
{% load crispy_forms_tags %}

<form id="CreateForm" method="post" hx-post="{{ request.path }}" role="form" hx-encoding="multipart/form-data">
    {% csrf_token %}

    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title fs-5 fw-bold" title="Createtitle">Create service</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">
            <div class="text-dark row">
                    
                {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}

                {% for field in form %}
                    <div class="col-12 col-md-6">
                        {{ field|as_crispy_field }}
                    </div>
                {% endfor %}

            </div>

            <div class="modal-footer">
                <button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button>
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </div>
    </div>
</form>

{% comment %} {% block js %}
<script>    
    let onchange_date = (value) => {
        var url = "{% url 'appointments:get_occupied_times' %}?date=" + value;
        //$('#time-select').load(url);
        //add options to select
        fetch(url)
            .then(response => response.json())
            .then(data => {
                let select = document.getElementById('id_time');
                select.innerHTML = '';
                let option = document.createElement('option');
                option.value = '';
                option.text = '-- Selecciona una hora --';
                select.appendChild(option);
                console.log(data);
                data.available_times.forEach(time => {
                    let option = document.createElement('option');
                    option.value = time;
                    option.text = time;
                    select.appendChild(option);
                });
            });
    }
</script>
{% endblock js %} {% endcomment %}

apps/appointments/templates/appointments/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Services{% endblock title %}

{% block css%}
<link rel="stylesheet" href="{% static 'assets/css/sb-admin-2.css' %}" />
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 my-4">
        </div>
        <div class="col-12 col-sm-6 col-md-6 d-flex justify-content-start align-items-center">
            <h1 class="fs-3 mb-4 fw-bold ">{{title}}</h1>
        </div>
        <div class="col-12 col-sm-6 col-md-6 d-flex justify-content-end align-items-center">
            <a class="btn btn-primary" role="button" href="#"
                data-bs-toggle="tooltip" data-bs-placement="top"
                hx-get="{% url 'appointments:create' %}"
                hx-target="#dialogCreate"
                hx-trigger="click"
                hx-swap="innerHTML"
            >
                <i class="fa fa-plus"></i> &nbsp;Agregar
            </a>
        </div>
    </div>

    {% include 'includes/filter.html' %}

    <div class="border rounded bg-white">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table rounded">
                        <thead>
                            <tr>
                                <th class="text-center">Service</th>
                                <th class="text-center">Date</th>
                                <th class="text-center">Hour</th>
                                <th class="text-center">Price</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for appointment in appointments %}
                                <tr class="text-center">
                                    <td>{{ appointment.service }}</td>
                                    <td>{{ appointment.date }}</td>
                                    <td>{{ appointment.time }}</td>
                                    <td>{{ appointment.price }}</td>
            
                                    <td class="text-center">
                                        {% comment %} <a href="{% url 'services:detail' pk=service.id %}" class="btn btn-info btn-sm">Detail</a> {% endcomment %}
                                        <a href="#"
                                            class="btn btn-primary btn-sm btn-circle"
                                            {% comment %} role="button"
                                            data-bs-toggle="tooltip"
                                            data-bs-placement="top"
                                            hx-get="{% url 'services:update' pk=service.id %}"
                                            hx-target="#dialogCreate"
                                            hx-trigger="click"
                                            hx-swap="innerHTML" {% endcomment %}
                                            >
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a class="btn btn-danger btn-sm btn-circle"
                                            {% comment %} role="button"
                                            data-bs-toggle="modal"
                                            onclick="destroy({{ service.id }})"
                                            data-bs-target="#delete-modal" {% endcomment %}
                                            href="#"
                                        >
                                            <i class="fa fa-trash"></i>
                                    </a>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="4" class="text-center text-white fw-bold bg-gray-700">No hay citas disponibles</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% include 'pagination.html' %}
        </div>
    </div>

</div>


<div class="modal fade" id="CreateModal" tabindex="-1" aria-labelledby="CreateModalLabel" aria-hidden="true">
    <div id="dialogCreate" class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg" hx-target="this">
        <!-- Aquí se cargará dinámicamente el contenido del modal con HTMX -->
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'assets/js/htmx-modal-create.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script>    

    htmx.on("htmx:afterSwap", (e) => {
        console.log("Contenido cargado, mostrando modal.");
        if (e.detail.target.id == "dialogCreate") {
            let select = document.getElementById('id_time');
            //add empty option
            let option = document.createElement('option');
            option.value = '';
            option.text = '-- Select a date first --';
            select.appendChild(option);

        }
    })

    let onchange_date = (value) => {
        console.log("Cambiando fecha");
        var url = "{% url 'appointments:get_occupied_times' %}?date=" + value;
        fetch(url)
            .then(response => response.json())
            .then(data => {
                let select = document.getElementById('id_time');
                select.innerHTML = '';
                let option = document.createElement('option');
                option.value = '';
                option.text = '-- Select a hour --';
                select.appendChild(option);
                console.log(data);
                data.available_times.forEach(time => {
                    let option = document.createElement('option');
                    option.value = time;
                    option.text = time;
                    select.appendChild(option);
                });
            });
    }

    {% comment %} document.getElementById("id_date").addEventListener("change", function(){
        var date = this.value;
        var url = "{% url 'appointments:get_occupied_times' %}?date=" + date;
        fetch(url)
            .then(response => response.json())
            .then(data => {

                console.log("correct");
                let select = document.getElementById('id_time');
                select.innerHTML = '';
                let option = document.createElement('option');
                option.value = '';
                option.text = '-- Selecciona una hora --';
                select.appendChild(option);
                console.log(data);
                data.available_times.forEach(time => {
                    let option = document.createElement('option');
                    option.value = time;
                    option.text = time;
                    select.appendChild(option);
                });
            });
    }) {% endcomment %}
</script>
{% endblock %}