apps/services/urls.py
from django.urls import path
from .views import (
    ServicesIndexView,
    ServicesCreateView,
    ServicesUpdateView,
    ServicesDeleteView,
)

app_name="services"

urlpatterns = [
    path('', ServicesIndexView.as_view(), name="index"),
    path('create/', ServicesCreateView.as_view(), name="create"),
    path('update/<int:pk>/', ServicesUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', ServicesDeleteView.as_view(), name="delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.home.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('services/', include('apps.services.urls')),
    path('appointments/', include('apps.appointments.urls')),
    path('',home_view, name='home'),
    #path("login/", home_view, name="login"),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/services/models.py
from django.db import models

# Create your models here.
from django.db import models

class Services(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = 'services'
        ordering = ["-id"]

    def __str__(self):
        return self.name
    

apps/services/forms.py
from django import forms
from django.forms import ModelForm
from .models import Services

class ServiceForm(ModelForm):
    class Meta:
        model = Services
        fields = ['name',  'price', 'description']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'min': 0}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

    def clean_name(self):
        name = self.cleaned_data.get('name')
        exists_name = Services.objects.filter(name__iexact=name).exclude(id=self.instance.id).exists()
        if exists_name:
            raise forms.ValidationError('This service name already exists')
        return name

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price <= 0:
            raise forms.ValidationError('Price must be greater than zero')
        return price

apps/services/views.py
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView
#import success message
from django.contrib.messages.views import SuccessMessageMixin
from django_filters.views import FilterView
from .models import Services
from .filters import ServiceFilter
from .forms import ServiceForm
# Create your views here.

class ServicesIndexView(LoginRequiredMixin, FilterView):
    model = Services
    template_name = 'services/index.html'
    context_object_name = 'services'
    filterset_class = ServiceFilter
    paginate_by = 10
    # filterset_fields = ['name']
    # ordering = ['name']
    # search_fields = ['name']

class ServicesCreateView(LoginRequiredMixin, CreateView):
    model = Services
    template_name = 'services/create2.html'
    form_class = ServiceForm
    success_url = reverse_lazy('services:index')

    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create Service'
        return context
    
    def post(self, request: HttpRequest, *args: str, **kwargs):
        self.object = None
        form = self.get_form()

        if not form.is_valid():
            context = self.get_context_data()
            context['form'] = form
            return render(request, self.template_name, context)
        
        self.object = form.save()
        # messages.success(request, 'Service was created successfully')
        return HttpResponse(200)

class ServicesUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Services
    template_name = 'services/create2.html'
    form_class = ServiceForm
    success_url = reverse_lazy('services:index')
    success_message = 'Service was updated successfully'

    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Service'
        return context
    
    def post(self, request: HttpRequest, *args: str, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if not form.is_valid():
            context = self.get_context_data()
            context['form'] = form
            return render(request, self.template_name, context)
        
        self.object = form.save()

        messages.success(request, 'Service was updated successfully')
        return HttpResponse(200)
    
class ServicesDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Services
    success_url = reverse_lazy('services:index')
    success_message = 'Service was deleted successfully'

apps/services/templates/services/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Services{% endblock title %}

{% block css%}
{% endblock %}

{% block content %}
<div class="container-fluid mb-1">
    <!-- Botón de volver atrás y título -->
    <div class="row">
        <div class="col-12 align-items-center">
            <a class="btn btn-secondary my-4" href="{% url 'services:index' %}">
                <i class="fas fa-arrow-left"></i>
            </a>
        </div>
    </div>


    <!-- Fin del título -->

    <!-- Formulario -->
    <div class="row justify-content-center m-sm-1">
        <h1 class="fs-3 fw-bold text-center">{{title}}</h1>
        <div class="col-lg-8 col-md-10 col-sm-12  bg-white border rounded p-4 shadow">
            <form method="post" class="text-black">
                {% csrf_token %}
                <div class="row g-3">
                    <!-- Recorremos los campos del formulario -->
                    {% for field in form %}
                        {% if field.field.widget.input_type == "text" or field.field.widget.input_type == "number" %}
                            <div class="col-12 col-md-6">
                                {{ field|as_crispy_field }}
                            </div>
                        {% else %}
                            <div class="col-12">
                                {{ field|as_crispy_field }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
    
                <!-- Botones de acción -->
                <div class="d-flex justify-content-end mt-4">
                    <a href="{% url 'services:index' %}" class="btn btn-secondary me-2" type="button">
                        <span class="icon text-white-50">
                            <i class="fas fa-arrow-left"></i>
                        </span>
                        <span class="text">Cancelar</span>
                    </a>
                    <button class="btn btn-primary" type="submit">
                        <span class="icon text-white-50">
                            <i class="fas fa-save"></i>
                        </span>
                        <span class="text">Guardar</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <!-- Fin del formulario -->
</div>


<a class="border rounded d-inline scroll-to-top" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
{% endblock %}

apps/services/templates/services/create2.html
{% load crispy_forms_tags %}
{% comment %} <form id="CreateForm" method="post" hx-post="{{request.path}}" role="form" hx-encoding="multipart/form-data">
    <div class="row" >
        <div class="col-md-12 bg-white" style="text-align: left;">
            <div class="row">
                {% for field in form %}
                    <div class="col-6">
                        {{field|as_crispy_field}}
                    </div>
                {% endfor %}
            </div>
            <div class="text-end m-0 p-2">
                <button class="btn btn-primary" type="submit">Guardar</button>
                <a href="{{ request.path }}" class="btn btn-secondary reset" type="button">Cancelar</a>
            </div>
        </div>
    </div>
</form> {% endcomment %}

<form id="CreateForm" method="post" hx-post="{{ request.path }}" role="form" hx-encoding="multipart/form-data">
    {% csrf_token %}
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title fs-5 fw-bold" title="Createtitle">Create service</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                {% comment %} <button type="button" class="" data-bs-dismiss="modal" aria-label="Close">x</button> {% endcomment %}
        </div>

        <div class="modal-body">
            <div class="text-dark row">
                    
                {% for field in form %}
                    {% if field.field.widget.input_type == "text" or field.field.widget.input_type == "number"  %}
                        <div class="col-12 col-md-6">
                            {{ field|as_crispy_field }}
                        </div>
                    {% else %}
                        <div class="col-12">
                            {{ field|as_crispy_field }}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            <div class="modal-footer">
                {% comment %} <button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button> {% endcomment %}
                <button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button>
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </div>
    </div>
</form>

{% comment %} <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
        <form id="CreateForm" method="post" hx-post="{{ request.path }}" role="form" hx-encoding="multipart/form-data">
            {% csrf_token %}
            <div class="modal-header">
                <h2 class="modal-title fs-5 fw-bold">Create service</h2>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="text-dark row">
                    
                    {% for field in form %}
                        <div class="col-6">
                            {{ field|as_crispy_field }}
                        </div>
                    {% endfor %}
                        
                </div>
            </div>

            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancelar</button>
                <button class="btn btn-primary" type="submit">Guardar</button>
            </div>
        </form>
    </div>
</div> {% endcomment %}

apps/services/templates/services/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Services{% endblock title %}

{% block css%}
<link rel="stylesheet" href="{% static 'assets/css/sb-admin-2.css' %}" />
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 my-4">
            {% comment %} <a class="anone" href="#">
                <i class="fa fa-long-arrow-left"></i>
                    <span>&nbsp; Volver</span>
            </a> {% endcomment %}
        </div>
        <div class="col-12 col-sm-6 col-md-6 d-flex justify-content-start align-items-center">
            <h1 class="fs-3 mb-4 fw-bold ">Titulo</h1>
        </div>
        <div class="col-12 col-sm-6 col-md-6 d-flex justify-content-end align-items-center">
            <a class="btn btn-primary" role="button" href="#"
                data-bs-toggle="tooltip" data-bs-placement="top"
                hx-get="{% url 'services:create' %}"
                hx-target="#dialogCreate"
                hx-trigger="click"
                hx-swap="innerHTML"
            >
                <i class="fa fa-plus"></i> &nbsp;Agregar
            </a>
            {% comment %} <a class="btn btn-primary" role="button" href="{% url 'services:create' %}">
                <i class="fa fa-plus"></i> &nbsp;Agregar
            </a> {% endcomment %}
        </div>
    </div>

    {% include 'includes/filter.html' %}

    <div class="border rounded bg-white">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table rounded">
                        <thead>
                            <tr>
                                <th class="text-center">Name</th>
                                <th class="text-center">Price</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for service in services %}
                                <tr class="text-center">
                                    <td>{{ service.name }}</td>
                                    <td>{{ service.price }}</td>
            
                                    <td class="text-center">
                                        {% comment %} <a href="{% url 'services:detail' pk=service.id %}" class="btn btn-info btn-sm">Detail</a> {% endcomment %}
                                        <a href="#"
                                            class="btn btn-primary btn-sm btn-circle"
                                            role="button"
                                            data-bs-toggle="tooltip"
                                            data-bs-placement="top"
                                            hx-get="{% url 'services:update' pk=service.id %}"
                                            hx-target="#dialogCreate"
                                            hx-trigger="click"
                                            hx-swap="innerHTML"
                                            >
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a class="btn btn-danger btn-sm btn-circle"
                                            role="button"
                                            data-bs-toggle="modal"
                                            onclick="destroy({{ service.id }})"
                                            data-bs-target="#delete-modal"
                                            href="#"
                                        >
                                            <i class="fa fa-trash"></i>
                                    </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% include 'pagination.html' %}
        </div>
    </div>

</div>
{% comment %} <div class="modal fade" id="CreateModal" tabindex="-1" aria-labelledby="CreateModalLabel" aria-hidden="true">
    <div id="dialogCreate" class="modal-dialog modal-dialog-scrollable modal-lg rounded" hx-target="this">
    </div>
</div>  {% endcomment %}

<div class="modal fade" id="CreateModal" tabindex="-1" aria-labelledby="CreateModalLabel" aria-hidden="true">
    <div id="dialogCreate" class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg" hx-target="this">
        <!-- Aquí se cargará dinámicamente el contenido del modal con HTMX -->
    </div>
</div>

<form id="deleteForm" method="post">
    {% csrf_token %}
    <div class="modal fade" role="dialog" tabindex="-1" id="delete-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title fs-5 color_guinda fw-bold">Delete element</h2>
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p class="fs-6 text-dark">If you delete this item, it will not be possible to recover it.</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancel</button>
                    <button class="btn btn-danger" type="button" onclick="formSubmit()">Delete</button>
                </div>
            </div>
        </div>
    </div>
</form>

<a class="border rounded d-inline scroll-to-top" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
{% endblock %}

{% block js %}

<script src="{% static 'assets/js/htmx-modal-create.js' %}"></script>

<script>
    function destroy(id) {
        let queryParams = new URLSearchParams(window.location.search);
        let url = "{% url 'services:delete' 1 %}";
        url = url.replace('1', id);
        url = url + '?' + queryParams.toString();
        $("#deleteForm").attr('action', url);
    }

    function formSubmit() {
        $("#deleteForm").submit();
    }
</script>
{% endblock %}